#! /bin/sh

cat $AGNER_PACKAGE_REPO/ire | sed -e "s|AGNER_INSTALL_PREFIX|$AGNER_INSTALL_PREFIX|g" > bin/ire
cat $AGNER_PACKAGE_REPO/reia | sed -e "s|AGNER_INSTALL_PREFIX|$AGNER_INSTALL_PREFIX|g" > bin/reia
cat $AGNER_PACKAGE_REPO/reiac | sed -e "s|AGNER_INSTALL_PREFIX|$AGNER_INSTALL_PREFIX|g" > bin/reiac

REIA_BIN_DIR=$AGNER_INSTALL_PREFIX/bin ERL_LIB_DIR=$AGNER_INSTALL_PREFIX rake install
