#!/bin/sh

USAGE="Usage: `basename $0` file.re"

if [ $# -eq 0 ]; then
	echo $USAGE >&2
	exit 1
fi

PROGRAM=$1
shift

REIA_HOME=AGNER_INSTALL_PREFIX/reia
export REIA_HOME
erl -pz AGNER_INSTALL_PREFIX/reia/ebin -noshell +K true -s reia init -s reia_internal execute_file $PROGRAM -s init stop -extra $*
